### ISSUE TITLE
[UE5] Whether Content/_*_ folders should be excluded?

### ISSUE THREAD

**Issue by LoneSimba** [MOZGIII/ue5-gitignore#5]
Good day! I've been configuring my UE5 project and when went to commit project files to git (decided to go with your ignore and attributes files) I've noticed two extra folders is Content, which seem to be containing some auto generated assets, related to map - their names are just [A-Z0-9]{;22}.uasset and and folder structure are just some autogen folders as well. I've been wondering, whether i should include them, or if they're auto generated by some build process they can be ignored?
![image](https://user-images.githubusercontent.com/6533959/185569727-4d07e771-e7c1-4d4d-a1be-70de5d7792d2.png)
![image](https://user-images.githubusercontent.com/6533959/185569771-71b0f82d-6357-4ea7-bd01-7f86d979425c.png)

**Comment by MOZGIII** [comment]
They have to be included in git (unless you want your levels to break), see https://docs.unrealengine.com/5.0/en-US/one-file-per-actor-in-unreal-engine/

**Comment by LoneSimba** [comment]
Oh, i see, thank you! Wish Rider IDE was able to disambiguate this as well - i commit to git using IDE since it's C++ project
